services:

  postgres:
    build:
      context: postgres_docker/
      dockerfile: Dockerfile_postgres
    environment:
      POSTGRES_USER: hr
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hr
      POSTGRES_INITDB_ARGS: '--encoding=UTF8 --lc-collate=ru_RU.UTF-8 --lc-ctype=ru_RU.UTF-8'
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "hr" ]

  memcached:
    image: memcached
    ports:
      - "11211:11211"
    command:
      - -m 64

  django_advanced:
    build:
      context: .
      dockerfile: ./Dockerfile
    # Пробрасываем 8000 порт контейнера на 8000 порт локалхоста(127.0.0.1:8000)
#    ports:
#      - "127.0.0.1:8000:8000"
    # Файл содержащий переменные окружения для контейнера
    env_file:
      - .env.prod
    environment:
      CACHES_LOCATION: memcached:11211
      POSTGRES_HOST: postgres
    command: gunicorn django_advanced.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started

  nginx:
    # Указываем директорию ./nginx, в которой содержится Dockerfile для сборки образа
    build: ./nginx
    # Пробрасываем 80 порт контейнера на 80 порт локальной машины(порт будет доступен из вне)
    ports:
      - 80:80
    # Дожидаемся запуска контейнера django_advanced
    depends_on:
      - django_advanced