# Generated by Django 6.0.2 on 2026-02-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_remove_employee_compensations_employee_about_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.CharField(default='default', max_length=10000),
            preserve_default=False,
        ),
    ]
