# Generated by Django 6.0.2 on 2026-02-23 13:59

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_alter_employee_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='about',
            field=models.CharField(max_length=10000),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.HashIndex(fields=['about'], name='hr_employee_about_ix'),
        ),
    ]
