# Generated by Django 6.0.2 on 2026-02-25 19:18

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_alter_employee_about_employee_hr_employee_about_ix'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='hr_employee_about_ix',
        ),
        migrations.AddIndex(
            model_name='employee',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created'], name='hr_employee_created_ix', pages_per_range=2),
        ),
    ]
